# Failure dictionary ported from get_cesium_data/sync_history.py
# Maps (BU, failure_keyword) -> (defect_class, defect_value, root_cause)

FAILURE_DICT = {
    "SRGBU": {
        "DATA_PLANE_TEST": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "RAMSIZE": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "MB_DIAG_TEST": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "CASTOR": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "IO_INTERFACE_TEST": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "RFID": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "SPARROW": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "DSL_DIAG_TEST": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "ENABLE_IOS": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "BOOT": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "RADIO_3G4G_TESTS": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "VERIFY_COOKIE": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "CLEAN": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "CONFIGURATION": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "COPY_THOUSANDEYES_IN_COOKIE": ("ORDER_ISSUE", "ORDER_MISSING_HARDWARE", "M2USB missing from order"),
        "ROMMON_INSTALL_DEV_KEY": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "CHECK_M2": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "ASSEMBLE_GENEALOGY": ("OPERATOR_PROCESS", "MISSED_SCAN", "operator scan wrong label"),
        "INSTALL_IOS": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "LOGIN_IOS": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "ADD_CHILD_TST": ("OPERATOR_PROCESS", "MISSED_SCAN", "operator scan wrong label"),
        "CHECK_PSU_COOKIE": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "CHECK_IOS_AND": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "CHECK_FAN": ("TEST", "POWER_INTERRUPT", "power interrupt"),
        "BOOT_TO_CASTOR_UBOOT": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "TEST_MOTHERBOARD": ("TEST", "SLOT_FAILURE", "BAD CONTACT"),
        "SET_IP_FOR_INSTALL": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "VERIFY_LICENSES": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "POWER_CYCLE_TEST": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "COPY_IOS_TO_FLASH": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "GET": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "CHASSIS": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "COUNTRY": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "PROD": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "RTC": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "UPGRADE_ROMMON_VERSION": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "CHECK_RESET_BUTTON": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "PROMPT": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "SLR": ("TEST", "NETWORK_ISSUE", "NETWORK ISSUE"),
        "SLE": ("TEST", "NETWORK_ISSUE", "NETWORK ISSUE"),
        "ACT2": ("TEST", "NETWORK_ISSUE", "NETWORK ISSUE"),
        "QUACK": ("TEST", "NETWORK_ISSUE", "NETWORK ISSUE"),
        "SL_INSTALLATION": ("TEST", "NETWORK_ISSUE", "NETWORK ISSUE"),
        "WDC": ("TEST", "NETWORK_ISSUE", "NETWORK ISSUE"),
        "NETWORK": ("TEST", "NETWORK_ISSUE", "NETWORK SLOW"),
        "TFTP": ("TEST", "NETWORK_ISSUE", "NETWORK SLOW"),
        "DOWNLOAD": ("TEST", "NETWORK_ISSUE", "NETWORK SLOW"),
        "DNLD": ("TEST", "NETWORK_ISSUE", "NETWORK SLOW"),
        "ABORTED": ("TEST", "NETWORK_ISSUE", "NETWORK SLOW"),
        "IOX": ("TEST", "POWER_INTERRUPT", "POWER INTERRUPT"),
        "SET_ROMMON_FPGA_REGISTER": ("TEST", "POWER_INTERRUPT", "POWER INTERRUPT"),
        "UPGRADE_ROMMON": ("TEST", "POWER_INTERRUPT", "POWER INTERRUPT"),
        "UPDATE_BIOS": ("TEST", "POWER_INTERRUPT", "POWER INTERRUPT"),
        "SIM": ("TEST", "EQUIPMENT_PROBLEM", "EQUIPMENT PROBLEM"),
        "LINK": ("TEST", "EQUIPMENT_PROBLEM", "EQUIPMENT PROBLEM"),
        "WIFI_TRAFFIC_TEST": ("TEST", "PACKET_DROPPED", "PACKET LOST"),
        "FORMAT_BOOTSTRAP": ("TEST", "SCRIPT_PROBLEM", "SCRIPT PROBLEM"),
        "INSTALL_LICENSE": ("TEST", "SCRIPT_PROBLEM", "SCRIPT PROBLEM"),
        "SWITCH_TRANSITIONAL_ROMMON": ("TEST", "SCRIPT_PROBLEM", "SCRIPT PROBLEM"),
        "RECORD": ("TEST", "SCRIPT_PROBLEM", "SCRIPT PROBLEM"),
        "CMPD": ("TEST", "CNF_FAILURE", "NOT UPDATE"),
        "PIM": ("SOFTWARE", "SW_ERROR_INTERRUPT", "FIRMWARE ISSUE"),
        "PLUGGABLE": ("SOFTWARE", "SW_ERROR_INTERRUPT", "FIRMWARE ISSUE"),
        "FIRMWARE": ("SOFTWARE", "SW_ERROR_INTERRUPT", "FIRMWARE ISSUE"),
        "MODEM": ("SOFTWARE", "SW_ERROR_INTERRUPT", "FIRMWARE ISSUE"),
        "CHECK_SIM_PRESENT": ("SOFTWARE", "SW_ERROR_INTERRUPT", "FIRMWARE ISSUE"),
        "CHECK_SUBSLOT_STATUS": ("SOFTWARE", "SW_ERROR_INTERRUPT", "FIRMWARE ISSUE"),
        "LTE": ("SOFTWARE", "SW_ERROR_INTERRUPT", "FIRMWARE ISSUE"),
        "BUNDLE": ("SOFTWARE", "SW_ERROR_INTERRUPT", "IOS BAD"),
        "CHECK_MEMORY_SIZE": ("OPERATOR_PROCESS", "MISASSEMBLED", "DIMM WRONG SLOT"),
        "INVENTORY": ("OPERATOR_PROCESS", "MISASSEMBLED", "MISASSEMBLED"),
        "RSSI_TRAFFIC_TEST": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "GPS": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "ACW_TEST": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "DCW_TEST": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "CONTINUITY_TEST": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "INITIALIZATION": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "POWER": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "CHECK_LED": ("OPERATOR_PROCESS", "INCORRECT_OPERATOR_RESPONSE", "INPUT WRONG ANSWER"),
        "PROGRAM_COOKIE": ("OPERATOR_PROCESS", "MISSED_SCAN", "WRONG SN"),
    },
    "CSPBU": {
        "BMC_BLADE_POWER_OFF": ("TEST", "NO_BOOT", "UUT cannot boot to diagnostics"),
        "BMC_BLADE_POWER_RESET": (
            "TEST",
            "RETEST_NO_DEBUG",
            "Retest without any debug action to try to reproduce failure",
        ),
        "CHECK_FILE_SANITY_LOAD_STATE_VMEDIA": (
            "TEST",
            "RETEST_NO_DEBUG",
            "Retest without any debug action to try to reproduce failure",
        ),
        "CHECK_UUID": ("TEST", "RETEST_NO_DEBUG", "Retest without any debug action to try to reproduce failure"),
        "LOAD_EFI_LOAD_STATE_EFI": (
            "TEST",
            "RETEST_NO_DEBUG",
            "Retest without any debug action to try to reproduce failure",
        ),
        "RUN_CEV": ("TEST", "RETEST_NO_DEBUG", "Retest without any debug action to try to reproduce failure"),
        "TEST_CPU_TEMP": ("TEST", "RETEST_NO_DEBUG", "One of CPU is temperature is too high after dimm PMEM test"),
        "ACK_SERVER": ("TEST", "RETEST_NO_DEBUG", "Ack blade server not response in UCSM"),
        "CHECK_MFGONLY_BMC": ("TEST", "RETEST_NO_DEBUG", "Blade can not power on"),
        "START_SEQUENCER": ("TEST", "SCRIPT_PROBLEM", "The SYSCEV's test script cannot include Chassis PID"),
        "UPDATE_BMC_TO_MFG": ("TEST", "RETEST_NO_DEBUG", "Blade power on error"),
        "GENERATE": ("TEST", "RETEST_NO_DEBUG", "ATTRIBUTES RETEST_NO_DEBUG TE Verify test script"),
        "SETUP_CHASSIS": ("TEST", "RETEST_NO_DEBUG", "IOM cannot boot to CMC mode"),
        "ACK_CHASSIS": ("TEST", "RETEST_NO_DEBUG", "Ack chassis not response in UCSM"),
        "CHECK_ASSY": ("TEST", "SCRIPT_PROBLEM", "Chassis PID check ASSY error"),
        "DUMP_OBFL_LOG": ("TEST", "RETEST_NO_DEBUG", "Some errors detected when DUMP_OBFL_LOG"),
        "SETUP_UUT_IP": ("TEST", "RETEST_NO_DEBUG", "The IOM card unable to connect test server"),
        "BODEGA_FACTORY_DEFAULT_LINUX": (
            "TEST",
            "RETEST_NO_DEBUG",
            "Retest without any debug action to try to reproduce failure",
        ),
        "CHECK_UPD_CNIC_FW": ("SOFTWARE", "BAD_DIAG_IMAGE", "Software size small error"),
        "SCAN_CHILDREN_INFO": ("OPERATOR_PROCESS", "FUNCTIONAL_AREACHECK", "Unit lost pre record"),
        "CHECK_BBU": ("OPERATOR_PROCESS", "INSERTION_WRONG", "BBU module not inserted properly"),
        "CHECK_HOST_POST_COMPLETE_IN_BMC": ("OPERATOR_PROCESS", "INSERTION_WRONG", "DIMM module not inserted properly"),
        "CHECK_PSU": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PSU module not inserted properly"),
        "CHECK_SEL_LOG_CORRECTABLE_ECC": ("OPERATOR_PROCESS", "INSERTION_WRONG", "DIMM module not inserted properly"),
        "CHECK_SEL_LOG_NON_RECOVERABLE": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU module not inserted properly"),
        "CHECK_SPROM_1": ("OPERATOR_PROCESS", "INSERTION_WRONG", "RAID module not inserted properly"),
        "CHK_SEL_CIMC": ("OPERATOR_PROCESS", "INSERTION_WRONG", "DIMM module not inserted properly"),
        "CHK_SEL_CIMC_HDD_DRIVE_FAULT": ("OPERATOR_PROCESS", "INSERTION_WRONG", "HDD module not inserted properly"),
        "CHK_SEL_CIMC_LOAD_STATE_CIMC": ("OPERATOR_PROCESS", "INSERTION_WRONG", "DIMM module not inserted properly"),
        "NO_DHCP_IP": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Network cable not inserted properly"),
        "NO DHCP IP": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Network cable not inserted properly"),
        "CHK_SEL_CIMC_PSU_NON_RECOVERABLE": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PSU module not inserted properly"),
        "CHK_SEL_CIMC_UPI_CORRECTABLE": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU module not inserted properly"),
        "CLEAR_SEL": ("OPERATOR_PROCESS", "INSERTION_WRONG", "DIMM module not inserted properly"),
        "CNF_CHECK_:_MISSING__UCS_HD": ("OPERATOR_PROCESS", "INSERTION_WRONG", "HDD not inserted properly"),
        "CNF_CHECK_:_MISSING__UCS_M2": ("OPERATOR_PROCESS", "INSERTION_WRONG", "HDD not inserted properly"),
        "CNF_CHECK_:_MISSING__UCS_SD": ("OPERATOR_PROCESS", "INSERTION_WRONG", "HDD not inserted properly"),
        "CNF_CHECK_:_MISSING__UCSC_MLOM_IRJ4": (
            "OPERATOR_PROCESS",
            "INSERTION_WRONG",
            "PCIE module not inserted properly",
        ),
        "CNF_CHECK_:_MISSING__UCSC_PCIE": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PCIE module not inserted properly"),
        "CNF_CHECK_:_MISSING__UCSC_PSU": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PSU module not inserted properly"),
        "CONFIG_SD": ("OPERATOR_PROCESS", "INSERTION_WRONG", "SD module not inserted properly"),
        "DISCOVER_M2_FLASH_LOAD_STATE_LINUX": (
            "OPERATOR_PROCESS",
            "INSERTION_WRONG",
            "M2 module not inserted properly",
        ),
        "DISCOVER_PCIE_CIMC": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PCIE module not inserted properly"),
        "DISCOVER_SATA_INTERPOSER": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Sata module not inserted properly"),
        "DISCOVER_SPROM_COMPONENTS_LOAD_STAT": (
            "OPERATOR_PROCESS",
            "INSERTION_WRONG",
            "Raid module not inserted properly",
        ),
        "DISK_TEST": ("OPERATOR_PROCESS", "INSERTION_WRONG", "HDD module not inserted properly"),
        "DISK_TEST_HDD_MISMATCH": ("OPERATOR_PROCESS", "INSERTION_WRONG", "HDD module not inserted properly"),
        "HIPOT BOND TEST": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Hipot cable not inserted properly"),
        "LOAD_LINUX_FOR_DISCOVERY_LOAD_STATE": ("OPERATOR_PROCESS", "INSERTION_WRONG", "DIMM not inserted properly"),
        "LSPCI_VIC_CHK_DEVICE": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PCIE not inserted properly"),
        "PMEM2_M2": ("OPERATOR_PROCESS", "INSERTION_WRONG", "DIMM not inserted properly"),
        "POWER_CYCLE_CIMC_L2": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU not inserted properly"),
        "PRE_SEL": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU not inserted properly"),
        "PRE_SEL_CPU": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU not inserted properly"),
        "PRE_SEL_DIMM_UNCORRECTABLE_ECC": ("OPERATOR_PROCESS", "DRAM_LOOSE", "DIMM not inserted properly"),
        "PRE_SEL_FRU_MB_POWER_ON": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PSU not inserted properly"),
        "PRE_SEL_HDD_DRIVE_FAULT": ("OPERATOR_PROCESS", "INSERTION_WRONG", "HDD not inserted properly"),
        "PRE_SEL_MEMHOT_PROCHOT": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU not inserted properly"),
        "PRE_SEL_NO_DHCP_IP": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Network cable not inserted properly"),
        "PRE_SEL_UPI_CORRECTABLE": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU not inserted properly"),
        "RECORD_SYSTEM_MAC": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Scaned wrong MAC info"),
        "RUN_BMC_DIAG_BASEBOARD": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PCIE not inserted properly"),
        "RUN_BMC_DIAG_FAN": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Fan not inserted properly"),
        "RUN_BMC_DIAG_GPIO": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PCIE not inserted properly"),
        "RUN_EFI_PCIX64": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PCIE not inserted properly"),
        "SET_DEDICATE_MODE": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Network cable not inserted properly"),
        "SET_DEDICATE_MODE_1": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Network cable not inserted properly"),
        "SET_DEDICATE_MODE_2": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Network cable not inserted properly"),
        "SSH_TIME_OUT_2_NO_DHCP_IP": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Network cable not inserted properly"),
        "SSH_TO_UUT": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Network cable not inserted properly"),
        "STORAGEADAPTER_STATUS_CHECK": ("OPERATOR_PROCESS", "INSERTION_WRONG", "RAID not inserted properly"),
        "UPDATE_CKPCIE_FW": ("OPERATOR_PROCESS", "INSERTION_WRONG", "PCIE not inserted properly"),
        "UPDATE_MFG_CIMC_LOAD_STATE_CIMC": (
            "OPERATOR_PROCESS",
            "INSERTION_WRONG",
            "Network cable not inserted properly",
        ),
        "UPDATE_MFG_CIMC_NO_DHCP_IP": ("OPERATOR_PROCESS", "CABLE_LOOSE", "Network cable not inserted properly"),
        "UPGRADE_HDD_FW_HSU_ISO": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CPU not inserted properly"),
        "UPGRAE_HDD_FW": ("OPERATOR_PROCESS", "INSERTION_WRONG", "RAID not inserted properly"),
        "DIMM:CNT": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Dimm can not be detected under BMC."),
        "PMEM2_M": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Some ECC errors were detected when running PMEM test"),
        "BOOT_HOST_TO_EFI": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Blade can not to power on"),
        "FINAL_COMPARE_CNF": (
            "OPERATOR_PROCESS",
            "INSERTION_WRONG",
            "HDD slot was unable to detected under linux diag test.",
        ),
        "AREA_CHECK": ("OPERATOR_PROCESS", "INSERTION_WRONG", "UUT test wrong station"),
        "VERIFY_PCIE_LINK": ("OPERATOR_PROCESS", "INSERTION_WRONG", "VERIFY_PCIE_LINK fail in linux"),
        "CHECK_SEL_LOG": (
            "OPERATOR_PROCESS",
            "INSERTION_WRONG",
            "Some ECC errors were detected when running PMEM test",
        ),
        "VERIFY_CRUZ_FW": ("OPERATOR_PROCESS", "INSERTION_WRONG", "VERIFY_CRUZ_FW fail"),
        "ENABLE_SD": ("OPERATOR_PROCESS", "INSERTION_WRONG", "ERROR Flexutil_write_attributes"),
        "CHECK_NETWORK": ("OPERATOR_PROCESS", "INSERTION_WRONG", "The IOM card unable to connect test server"),
        "RUN_PCIX64": ("OPERATOR_PROCESS", "INSERTION_WRONG", "VERIFY_PCIE_LINK fail in linux"),
        "DISABLE_REBOOT": ("OPERATOR_PROCESS", "INSERTION_WRONG", "IOM cannot boot to CMC mode"),
        "BLADE_CHECK_FAULT": ("OPERATOR_PROCESS", "INSERTION_WRONG", "CIMC did not detect storage controller in UCMS"),
        "TRAFFIC_TEST": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Port Link is down"),
        "PRE_SEL_DIMM_UNCORRECTABLE": (
            "OPERATOR_PROCESS",
            "INSERTION_WRONG",
            "Some ECC errors were detected when running PMEM test",
        ),
        "I2c": ("OPERATOR_PROCESS", "INSERTION_WRONG", "i2c connectivity test failed"),
        "CHECK_FAN_SPEED": ("OPERATOR_PROCESS", "INSERTION_WRONG", "Chassis fan speed control error"),
    },
    "UABU": {
        "VOLTAGE_TEST": ("TEST", "RETEST_NO_DEBUG", "Check the voltage status failed."),
        "VERIFY_HW_AUTH": ("TEST", "RETEST_NO_DEBUG", "failed to check stack cable connection status"),
        "STACK_RAC_TEST": ("TEST", "RETEST_NO_DEBUG", "check the parameters of stack cable failed"),
        "ACT2_DSC_2": ("TEST", "SCRIPT_PROBLEM", "Timeout occurs during power cycle"),
        "RELOAD_SYSTEM_AFTER_CLEAR_CONFIG": ("TEST", "RETEST_NO_DEBUG", "Receive expectphrase time out."),
        "MODE_IOSE": ("TEST", "RETEST_NO_DEBUG", "Failed to go to Switch# mode and then time out."),
        "MODE_BTL": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "ACT2_DSC_1": ("TEST", "SCRIPT_PROBLEM", "Timeout occurs during power cycle"),
        "TFTP_BOOTING_IOS": ("TEST", "NETWORK_ISSUE", "Download time out"),
        "BOOT_TO_IPXE": ("TEST", "RETEST_NO_DEBUG", "Failed to open console."),
        "INSTALL_SLR": ("TEST", "RETEST_NO_DEBUG", "delete license timeout"),
        "INSTALL_SLE": ("TEST", "RETEST_NO_DEBUG", "delete license timeout"),
        "INSTALL_THOUSANDEYES": ("TEST", "RETEST_NO_DEBUG", "Receive expectphrase time out."),
        "LOAD_DSC_PCAMAP": ("TEST", "RETEST_NO_DEBUG", "delete license timeout"),
        "VERIFY_PID": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "IPXE_BOOT_DIAGNOSTICS": ("TEST", "RETEST_NO_DEBUG", "Timeout during loading diag image"),
        "INSTALL_IOS-XR_FROM_IPXE": ("TEST", "RETEST_NO_DEBUG", "Timeout during install XR image"),
        "WAIT_FOR_IOS_BOOT_UP": ("TEST", "SCRIPT_PROBLEM", "Fail to power on again"),
        "VERIFY_CABLE_SERNUM": ("TEST", "RETEST_NO_DEBUG", "failed to check stack cable connection status"),
        "BOOT_IOS": ("TEST", "SW_ERROR_INTERRUPT", "IOS Reboot"),
        "PREPARE_IOS_IMAGES": ("TEST", "DOWNLOAD_BAD", "The ordered IOS Image does not in server."),
        "READ_PERIPH": ("TEST", "RETEST_NO_DEBUG", "failed to check stack cable connection status"),
        "INSTALL_MAIN_IOS_IMAGE": ("TEST", "RETEST_NO_DEBUG", "download images time out"),
        "STACK_RAC": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "CNF_CHECK": ("ORDER_ISSUE", "ORDER_MISSING_HARDWARE", "hardware missing from order"),
        "INSTALL_SFR": ("SOFTWARE", "IMAGE_CORRUPT", "Run IOS image file stopped or hangs up with the 9.14 version"),
        "CHECK_BIOS_IMAGE_CORRUPT": (
            "SOFTWARE",
            "IMAGE_CORRUPT",
            "IOS image file stopped or hangs up with the 9.14 version",
        ),
        "INSTALL_SFR_PATCHES": (
            "SOFTWARE",
            "IMAGE_CORRUPT",
            "Run IOS image file stopped or hangs up with the 9.14 version",
        ),
        "FINAL_CHECK": ("SOFTWARE", "IMAGE_CORRUPT", "Run IOS image file stopped or hangs up with the 9.14 version"),
        "SHOW_LOGGING": (
            "SOFTWARE",
            "SW_ERROR_INTERRUPT",
            'The system catch error message "A config-err error has occurred"',
        ),
        "VERIFY_SHMOO_FILE": ("SOFTWARE", "SW_ERROR_INTERRUPT", "Tuning value out of range."),
        "GET_SHMOO_FILE_SW_ERROR_INTERRUPT": (
            "SOFTWARE",
            "SW_ERROR_INTERRUPT",
            "Failed to generate shmoo file after retry 5 times",
        ),
        "GET_PRINTER_CONNECTION": ("TEST", "AUTOTEST_SERVER_DOWN", "CONSOLE FREEZING"),
        "INSTALL_OPTION_PACKAGES": ("SOFTWARE", "IMAGE_CORRUPT", "Software Reload"),
        "GRACEFUL_RELOAD": ("SOFTWARE", "IMAGE_CORRUPT", "Software Reload"),
        "CISCO_ASA": ("SOFTWARE", "IMAGE_CORRUPT", "Run IOS image file stopped or hangs up with the 9.14 version"),
        "FIND_SHMOO_FILE": ("SOFTWARE", "SW_ERROR_INTERRUPT", "Tuning value out of range."),
        "HIPOT_VOLTAGE_TEST": (
            "OPERATOR_PROCESS",
            "INCORRECT_OPERATOR_RESPONSE",
            "The operator touched the sensor and the power was cut off",
        ),
        "SERDES_EYE": ("OPERATOR_PROCESS", "CABLE_LOOSE", "reinsert and retest passed"),
        "SCAN_CHILDREN_INFO": ("OPERATOR_PROCESS", "FUNCTIONAL_AREACHECK", "DIMM or HDD missed PCBDL record"),
        "SCAN CHILDREN INFO": ("OPERATOR_PROCESS", "FUNCTIONAL_AREACHECK", "DIMM or HDD missed PCBDL record"),
        "SYSINIT": ("OPERATOR_PROCESS", "CABLE_LOOSE", "reinsert and retest passed"),
        "SERDES_EYE_NIF_TEST": ("OPERATOR_PROCESS", "CABLE_LOOSE", "reinsert and retest passed"),
        "SERDES_EYE_SIF_TEST": ("OPERATOR_PROCESS", "CABLE_LOOSE", "reinsert and retest passed"),
    },
    "WNBU": {
        "VERIFY_MB_MAC": ("OPERATOR_PROCESS", "LABEL_ISSUE", "Wrong SN"),
        "VERIFY_SN_PN_HWREV": ("OPERATOR_PROCESS", "MISSED_SCAN", "Operator scan incorrect barcodes on traveler"),
        "ADD_BOARD_TST_DATA": ("ORDER_ISSUE", "LINE_ID_ISSUE", "Line id missing SW"),
        "ACT2_VALIDATE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "AIR": ("TEST", "PRESSURE", "TEST RETEST_NO_DEBUG Retest PASS"),
        "BOOT": ("TEST", "CUSTOMER", "IMAGE NO_BOOT UUT cannot boot to IOS"),
        "BOOT_CUSTOMER_OS": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "BOOT_MFG_RCV_MENU": ("TEST", "NO_BOOT", "UUT cannot boot to IOS"),
        "CHECK": ("TEST", "VERSION", "AND UPGRADE REL U-BOO RETEST_NO_DEBUG Retest PASS"),
        "CHECK_FIRMWARE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "CHECK_MEMORY_ADDRESS": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "CHECK_MFG_IMAGE_VERSION": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "CHECK_PCA_AND_PART_NUMBER": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "CUSTOM_IMAGE_PING_TEST": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "CHECK_RADIO_PART_1": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "CHECK_RADIO_PART_2": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "CHECK_UUT_BOOTUP": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "CLEAR_ARP": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "DOWNLOAD_BOOTLOADER_IMAGE": ("TEST", "NETWORK_ISSUE", "Case is INC3026628"),
        "DOWNLOAD_BOOTM_IMAGE": ("TEST", "NETWORK_ISSUE", "Case is INC3026628"),
        "DOWNLOAD_CUSTOMER_IMAGE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "DOWNLOAD_DIAG": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "DOWNLOAD_DIAG_PART_1": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "DOWNLOAD_DIAG_PART_2": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "DOWNLOAD_MFG_IMAGE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "DOWNLOAD_SECURE_BOOT": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "DOWNLOAD_UBOOT_IMAGE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "DOWNLOAD_UBOOT_MFG": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "FETCH_VID": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "FINAL": ("TEST", "BOOT", "CUSTOMER IMAGE RETEST_NO_DEBUG Retest PASS"),
        "FINAL_PING_TEST": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "FINALIZE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "INITIALIZE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "LOAD": (
            "TEST",
            "PRODUCTION",
            "IMAGE IN PART DEFECTIVE_TESTER_CABLE Tester cable console defective or damaged",
        ),
        "LOAD_RECOVER_IMAGE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "LOAD_RTOS_IMAGE": ("TEST", "DEFECTIVE_TESTER_CABLE", "Tester cable console defective or damaged"),
        "LOG_VERIFY": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "MAC_VERIFY": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "MGMT": (
            "TEST",
            "LAN",
            "POE IN UBOOT PING TEST 1 DEFECTIVE_TESTER_CABLE Tester cable console defective or damaged",
        ),
        "PCIE_DETECTED_NO_LINK_RT": ("TEST", "AUTOTEST_SERVER_DOWN", "Apollo server issue"),
        "PRINT": ("TEST", "POD", "LABEL AUTOTEST_SERVER_DOWN Apollo server issue"),
        "PRINT_LABELS": ("TEST", "AUTOTEST_SERVER_DOWN", "Apollo server issue"),
        "PROG_COOKIE": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "PROGRAM_COOKIE": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "PROG_ASSY_COOKIE": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "PROG_FUNCTIONAL_COOKIE": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "PROGRAM_X509_SHA1": ("TEST", "NETWORK_ISSUE", "Retest PASS"),
        "PROGRAM_X509_SHA2": ("TEST", "NETWORK_ISSUE", "Retest PASS"),
        "POE_CONNECTION_ISSUE": ("TEST", "NETWORK_ISSUE", "Retest PASS"),
        "RADIO_U1_DEFECT_RT": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "READ_MB_SN_PN": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "RECORD_MB_MAC": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "READ_COOKIE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "RELOAD": ("TEST", "AFTER", "COOKIE PROGRAMMING RETEST_NO_DEBUG Retest PASS"),
        "RESTART_TO_UBOOT": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "RUN_PRIMARY_IMAGE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "SECURE_BOOT": ("TEST", "SCRIPT_PROBLEM", "Test script problems"),
        "SET": ("TEST", "U-BOOT", "BOOT ENV CONFIG RETEST_NO_DEBUG Retest PASS"),
        "SET_ENV_DEFAULT": ("TEST", "DEFECTIVE_TESTER_CABLE", "Tester cable defective or damaged"),
        "SET_FACTORY_ENV": ("TEST", "DEFECTIVE_TESTER_CABLE", "Tester cable defective or damaged"),
        "SET_FINALY_DEFAULT": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "SET_LAST_DEFAULT": ("TEST", "DEFECTIVE_TESTER_CABLE", "Tester cable defective or damaged"),
        "SHA1_AND_SHA2_VERIFY": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "SYSFT_ADD_TST_DATA": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "UNSET_CONFIG": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "VALIDATE_ACT2": ("TEST", "NETWORK_ISSUE", "Open case to fix it"),
        "VERIFY_PID_VID": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "VERIFY_SN_PN": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "VALIDATE_SWSUDI": ("TEST", "NETWORK_ISSUE", "Open case to fix it"),
        "VALIDATE_X509_SHA1": ("TEST", "NETWORK_ISSUE", "Open case to fix it"),
        "VALIDATE_X509_SHA2": ("TEST", "NETWORK_ISSUE", "Open case to fix it"),
        "VERIFY_COOKIE": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "VERIFY_RADIO_SN_PN": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "VERIFY_MAC": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "X509": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
        "VERIFY_SECURE_BOOT": ("TEST", "RETEST_NO_DEBUG", "Retest PASS"),
    },
    "CABU": {
        "SOFTWARE DOWNLOAD": ("TEST", "DOWNLOAD_BAD", "IMAGE DOWNLOAD FAIL"),
        "POWER CYCLE": ("TEST", "NETWORK_ISSUE", "NOT POWER CYCLE"),
        "CHECK SUPS DATE TIME": ("TEST", "CNF_FAILURE", "CAPTURE ERROR"),
        "BOOT IOS": ("TEST", "SINGLE_SUP", "NO_BOOT IOS BOOT FAIL"),
        "BOOT UP DIAGS": ("TEST", "DIAG_MISSING", "DIAGS BOOT FAIL"),
        "BRING UP CABLE MODEM PROCESS": ("OPERATOR_PROCESS", "INSERTION_WRONG", "MODULE CRAD RR"),
    },
    "INSBU": {
        "SUP": ("TEST", "RETEST_NO_DEBUG", "RETEST PASS"),
        "OS_ONLINE_DIAG": ("TEST", "RETEST_NO_DEBUG", "RETEST PASS"),
        "MARGIN": ("TEST", "DEFECTIVE_TESTR_CABLE", "BAD CONTACT"),
        "HIPOT": ("TEST", "DEFECTIVE_TESTR_CABLE", "BAD CONTACT"),
        "ADT_GETSEC": ("TEST", "NETWORK_ISSUE", "Open case to AT to fix"),
        "ADT_INST": ("TEST", "COULD_NOT_CLASSIFY", "Retest under no debug action"),
        "ADT_VER": ("TEST", "COULD_NOT_CLASSIFY", "Retest under no debug action"),
    },
    "ERBU": {
        "ERROR_ME": ("OPERATOR_PROCESS", "MISSED_SCAN", "WRONG SN"),
        "NO_ACOUNT": ("OPERATOR_PROCESS", "INCORRECT_OPERATOR_RESPONSE", "INPUT WRONG ANSWER"),
        "SYSTEM_COMPARE": ("OPERATOR_PROCESS", "MISSED_SCAN", "WRONG SN"),
        "SYNC_MASTER": ("OPERATOR_PROCESS", "INCORRECT_OPERATOR_RESPONSE", "INPUT WRONG ANSWER"),
        "LED_CHECK": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
        "CHECK_LC": ("OPERATOR_PROCESS", "CABLE_LOOSE", "CABLE LOOSE"),
    },
}

# BU prefix patterns for auto-detection
BU_PREFIX = {
    "^CBR-|RPHY": "CABU",
    "^820|8800|8804|8808|8812|8818|FAN-1RU|FAN-2RU|NC55-|NC57-|NCS-55|PSU2KW-|PSU4|PSU6": "CRBU",
    "^HX|N20-|N2XX|UCSB-|UCSC-|UCS-FI-|UCS-HD|UCS-IOM|UCS-M2|UCS-SD|UCS-TPM|UCS-SP|UCSS-S|UCS-CPU|UCS-M|UCS-S|UCS-U|UCSX": "CSPBU",
    "^AIR-|C910|C911|C912|C913|C9800|CW9164|CW9166": "WNBU",
    "^A900-|A902-|A903-|A907-|A920-|ASR-902|ASR-903|ASR-907|ASR-920|ME1200|N520-|N540|N560|NCS420|NCS421|NCS560|C9300-": "PABU",
    "^APIC-|CN611|N3K-|N9K-|NXA-|NXM-": "INSBU",
    "^A9903-|A99-|A9K-|ASR-9|PWR-1\\.6KW|PWR-2KW|PWR-3KW|PWR-4\\.4KW|PWR-6KW|8800-|88-LC|A900-": "ERBU",
}


def lookup_failure(bu, failure_keyword):
    """Look up root cause from failure dictionary.

    For SRGBU/CSPBU: uses substring matching (failure_keyword in failure_symptom)
    For others: uses exact match

    Returns: (defect_class, defect_value, root_cause) or None
    """
    if bu not in FAILURE_DICT:
        return None

    bu_dict = FAILURE_DICT[bu]

    if bu in ("SRGBU", "CSPBU"):
        # Substring matching
        for key, value in bu_dict.items():
            if key in failure_keyword:
                return value
    else:
        # Exact match first
        if failure_keyword in bu_dict:
            return bu_dict[failure_keyword]
        # Then try substring match as fallback
        for key, value in bu_dict.items():
            if key in failure_keyword:
                return value

    return None
